<?php

use yii\db\Migration;

class m180203_075020_create_table_tb_methods extends Migration
{
    public function safeUp()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable('{{%tb_methods}}', [
            'id' => $this->integer(11)->notNull()->append('AUTO_INCREMENT PRIMARY KEY'),
            'title' => $this->string(255)->notNull(),
            'lablist' => $this->integer(11)->notNull(),
            'goods_category' => $this->integer(11)->notNull(),
            'prime_price' => $this->double()->notNull(),
            'price' => $this->double()->notNull(),
            'active' => $this->integer(11)->notNull(),
            'status' => $this->smallInteger(4)->notNull(),
        ], $tableOptions);

        $this->insert('{{%tb_methods}}',['id'=>'1','title'=>'ТТГ  ','lablist'=>'1341386298','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'2','title'=>'АЛТ HUMAN','lablist'=>'1341400352','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'3','title'=>'ТТГ HUMAN','lablist'=>'1341386298','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'4','title'=>'ССГ','lablist'=>'1404551817','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'5','title'=>'ЛГ  ','lablist'=>'1341385945','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'6','title'=>'АТТГ-XEMA','lablist'=>'1372917846','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'7','title'=>'АТТГ-ALKOR','lablist'=>'1372917846','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'8','title'=>'Глобулин  ','lablist'=>'1430715613','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'9','title'=>'АЛТ  ','lablist'=>'1341400352','goods_category'=>'1507197742','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'10','title'=>'Myco IgG Best','lablist'=>'1341396055','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'11','title'=>'Anti - HBc  ','lablist'=>'1341389053','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'12','title'=>'ПТИ','lablist'=>'1356581588','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'13','title'=>'МНО','lablist'=>'1366871465','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'14','title'=>'Тромбиновое время','lablist'=>'1391663083','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'15','title'=>'АЧТВ','lablist'=>'1341488563','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'16','title'=>'Фибриноген','lablist'=>'1341488583','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'17','title'=>'АЧТВ (соотношение)','lablist'=>'1431949076','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'18','title'=>'Тромбиновое время (соотношение)   ','lablist'=>'1431949040','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'19','title'=>'Протромбимовое время','lablist'=>'1431948998','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'20','title'=>'Экспресс-HBsAg','lablist'=>'1341484897','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'21','title'=>'Экспресс-HCV','lablist'=>'1341484983','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'22','title'=>'Реакция Вассермана (RW)','lablist'=>'1341483794','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'23','title'=>'Время свертываемости крови','lablist'=>'1431949740','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'24','title'=>'Ретикулоциты','lablist'=>'1431949678','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'25','title'=>'Скорость оседания эритроцитов(ESR)','lablist'=>'1341384690','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'26','title'=>'Toxoplasma Gondii IgG','lablist'=>'1341391074','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'27','title'=>'Cytomegalovirus IgG','lablist'=>'1431943060','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'28','title'=>'Herpes Simlex 1/2 IgG','lablist'=>'1341395856','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'29','title'=>'Herpes Simplex 2 IgG','lablist'=>'1341395420','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'30','title'=>'Ureaplasma urealyticum IgG','lablist'=>'1341396152','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'31','title'=>'Chlamydia trachomatis IgG','lablist'=>'1341395944','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'32','title'=>'Rubella IgG','lablist'=>'1341391434','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'33','title'=>'Toxoplasma Gondii IgM','lablist'=>'1341391184','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'34','title'=>'Cytomegalovirus IgM','lablist'=>'1341391395','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'35','title'=>'Herpes Simplex 1/2 IgM','lablist'=>'1341395833','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'36','title'=>'Mycoplasma hominis IgA','lablist'=>'1341396003','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'37','title'=>'Ureaplasma urealyticum IgA','lablist'=>'1341396101','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'38','title'=>'Chlamydia trachomatis IgM','lablist'=>'1341395925','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'39','title'=>'Rubella IgM','lablist'=>'1341391528','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'40','title'=>'Бруцеллез (Brucella abortus)','lablist'=>'1431946539','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'41','title'=>'Туберкулёз(Hexagon TB)','lablist'=>'1431946660','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'42','title'=>'Helicobacter pylori (суммарные антитела)','lablist'=>'1341396407','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'43','title'=>'Candida IgG','lablist'=>'1341399552','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'44','title'=>'Candida IgM','lablist'=>'1341399574','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'45','title'=>'Chlamydia pneumoniae IgG','lablist'=>'1341396257','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'46','title'=>'Trichomonas vaginalis IgG','lablist'=>'1341399247','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'47','title'=>'Salmonella','lablist'=>'1431947198','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'48','title'=>'Anti-HAV IgM','lablist'=>'1341388899','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'49','title'=>'HBsAg Кол','lablist'=>'1341388948','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'50','title'=>'HBs Ag (ультра)','lablist'=>'1431945668','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'51','title'=>'Anti - HBs Ag','lablist'=>'1341389013','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'52','title'=>'HBe Ag','lablist'=>'1341389206','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'53','title'=>'Аnti - НCV','lablist'=>'1341389226','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'54','title'=>'Аnti - НCV','lablist'=>'1430451712','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'55','title'=>'Лямблии суммарные','lablist'=>'1341388529','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'56','title'=>'Аскарида IgG','lablist'=>'1341388718','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'57','title'=>'Тироксин общий Т4 HUMAN','lablist'=>'1341386546','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'58','title'=>'Тироксин общий Т4  ','lablist'=>'1341386546','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'59','title'=>'Трийодтиронин общий','lablist'=>'1341386496','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'60','title'=>'Трийодтиронин общий Т3  ','lablist'=>'1341386496','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'61','title'=>'Свободный тестостерон DBC','lablist'=>'1341386706','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'62','title'=>'HCG','lablist'=>'1341387295','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'63','title'=>'АТ-ТПО XEMA','lablist'=>'1431762322','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'64','title'=>'Тироксин свободный Т4 HUMAN','lablist'=>'1341386525','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'65','title'=>'Тироксин свободный Т4  ','lablist'=>'1341386525','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'66','title'=>'Трийодтиронин свободный Т3 HUMAN','lablist'=>'1341386453','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'67','title'=>'Трийодтиронин свободный Т3  ','lablist'=>'1341386453','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'68','title'=>'ФСГ HUMAN','lablist'=>'1341385990','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'69','title'=>'фсг Vitros','lablist'=>'1341385990','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'70','title'=>'ЛГ HUMAN','lablist'=>'1341385945','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'71','title'=>'Прогестерон DC','lablist'=>'1341385885','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'72','title'=>'Эстрадиол Е2 HUMAN','lablist'=>'1341386033','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'73','title'=>'Пролактин HUMAN','lablist'=>'1341385903','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'74','title'=>'Пролактин  ','lablist'=>'1341385903','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'75','title'=>'Тестостерон HUMAN','lablist'=>'1341386648','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'76','title'=>'Кортизол','lablist'=>'1341385867','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'77','title'=>'DHEA-S     XEMA','lablist'=>'1341386885','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'78','title'=>'СТГ','lablist'=>'1341386079','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'79','title'=>'Оксипрогестерон','lablist'=>'1341387459','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'80','title'=>'Эстриол E3 HUMAN','lablist'=>'1341386050','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'81','title'=>'Тиреоглобулин DC','lablist'=>'1430206456','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'82','title'=>'Поглощение Т3  ','lablist'=>'1431762512','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'83','title'=>'AHA ','lablist'=>'1432012895','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'84','title'=>'(АФС) IgM ORGENTIC','lablist'=>'1432013775','goods_category'=>'1507177890','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'85','title'=>'(АФС) IgG ORGENTIC','lablist'=>'1432013822','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'86','title'=>'Анти к Кард IgG ORGENTIC','lablist'=>'1432028486','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'87','title'=>'ИФР Mediagnost','lablist'=>'1341386175','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'88','title'=>'Рецепторам ТТГ Medizym','lablist'=>'1431762714','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'89','title'=>'Кальцитонин BIOMERICA','lablist'=>'1431762919','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'90','title'=>'2-гликопротеину ORGENTIC','lablist'=>'1432028661','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'91','title'=>'АКТГ','lablist'=>'1376638551','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'92','title'=>'Паратгормон ','lablist'=>'1376646059','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'93','title'=>'Паратгормон  ','lablist'=>'1376646059','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'94','title'=>'Anti SLA/LP lgG ','lablist'=>'1431770259','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'95','title'=>'Anti LKM1 ','lablist'=>'1431769903','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'96','title'=>'АМG BECKMAN','lablist'=>'1374844971','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'97','title'=>'Альдестерон DBC','lablist'=>'1432354958','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'98','title'=>'Ренин IBL','lablist'=>'1432356248','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'99','title'=>'Иммуноглобулин А VECTOR BEST','lablist'=>'1341485902','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'100','title'=>'Иммуноглобулин M VECTOR BEST','lablist'=>'1341485961','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'101','title'=>'Иммуноглобулин G  VECTOR BEST','lablist'=>'1341486016','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'102','title'=>'АФП HUMAN','lablist'=>'1341387505','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'103','title'=>'АФП  ','lablist'=>'1341387505','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'104','title'=>'СЕА HUMAN','lablist'=>'1341387540','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'105','title'=>'СЕА  ','lablist'=>'1341387540','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'106','title'=>'Свободный ПСА HUMAN','lablist'=>'1341387685','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'107','title'=>'CA 15-3 HUMAN','lablist'=>'1341387735','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'108','title'=>'CA 19-9 XEMA','lablist'=>'1341387776','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'109','title'=>'CA 19-9  ','lablist'=>'1341387776','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'110','title'=>'СА 19-9 HUMAN','lablist'=>'1341387776','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'111','title'=>'CA 125 HUMAN','lablist'=>'1341387817','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'112','title'=>'β-HCG HUMAN','lablist'=>'1341388005','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'113','title'=>'β-HCG  ','lablist'=>'1341388005','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'114','title'=>'общий ПСА HUMAN','lablist'=>'1341387625','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'115','title'=>'общий ПСА  ','lablist'=>'1341387625','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'116','title'=>'СК-МВ  ','lablist'=>'1431932894','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'117','title'=>'Тропонин I ES  ','lablist'=>'1341399627','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'118','title'=>'Миоглобин  ','lablist'=>'1431932771','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'119','title'=>'NT-PRO  ','lablist'=>'1431932846','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'120','title'=>'Иммуноглобулин Е HUMAN','lablist'=>'1341388803','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'121','title'=>'Эозинофилы','lablist'=>'1431950872','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'122','title'=>'Клещ домашней пыли XEMA','lablist'=>'1432018231','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'123','title'=>'Эпителий кошки XEMA','lablist'=>'1432018311','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'124','title'=>'Шерсть собаки XEMA','lablist'=>'1432018339','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'125','title'=>'Перо постельное XEMA','lablist'=>'1432018371','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'126','title'=>'Аллерген аскариды  XEMA','lablist'=>'1432018424','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'127','title'=>'Раннецветущие деревья XEMA','lablist'=>'1432018466','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'128','title'=>'Мучная смесь XEMA','lablist'=>'1432018490','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'129','title'=>'Детский пищевой микст XEMA','lablist'=>'1432018524','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'130','title'=>'Яичный желток XEMA','lablist'=>'1432018578','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'131','title'=>'Яичный белок XEMA','lablist'=>'1432018605','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'132','title'=>'Компоненты молока XEMA','lablist'=>'1432018628','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'133','title'=>'Цитрусовый микст 19 XEMA','lablist'=>'1432018659','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'134','title'=>'Фрукты и ягоды XEMA','lablist'=>'1432018688','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'135','title'=>'Орехи микст 34 XEMA','lablist'=>'1432018712','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'136','title'=>'Кровь на эозинофилы XEMA','lablist'=>'1431950823','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'137','title'=>'AFP  ','lablist'=>'1431931009','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'138','title'=>'AFP HUMAN','lablist'=>'1431931009','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'139','title'=>'Свободный эстриол HUMAN','lablist'=>'1431931145','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'140','title'=>' (β-ХГЧ) HUMAN','lablist'=>'1431931220','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'141','title'=>' (β-ХГЧ)  ','lablist'=>'1431931220','goods_category'=>'1507177890','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'142','title'=>'ПАББ-А XEMA','lablist'=>'1431931317','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'143','title'=>'Кортизол в крови HUMAN','lablist'=>'1431933031','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'144','title'=>'Кортизол в крови  ','lablist'=>'1431933031','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'145','title'=>'NТx  ','lablist'=>'1431933075','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'146','title'=>'iPTH (Паратгормон)','lablist'=>'1431933131','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'147','title'=>'iPTH (Паратгормон)  ','lablist'=>'1431933131','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'148','title'=>'Total Vitamin D  ','lablist'=>'1431933260','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'149','title'=>'АСТ HUMAN','lablist'=>'1341400401','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'150','title'=>'АСТ  ','lablist'=>'1341400401','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'151','title'=>'Билирубин  ','lablist'=>'1431776298','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'152','title'=>'Билирубин коньюгир.','lablist'=>'1431776432','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'153','title'=>'Билирубин неконьюгир.','lablist'=>'1431776480','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'154','title'=>'Кислая фосфатаза HUMAN','lablist'=>'1341401140','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'155','title'=>'СК  ','lablist'=>'1341400474','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'156','title'=>'СКМВ  ','lablist'=>'1341400645','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'157','title'=>'СК/СК-МВ  ','lablist'=>'1431773465','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'158','title'=>'СК/СК-МВ ***  ','lablist'=>'1432017063','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'159','title'=>'Мочевина  ','lablist'=>'1341400681','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'160','title'=>'Креатинин  ','lablist'=>'1341400544','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'161','title'=>'Соотношение мочевины и креатинина  ','lablist'=>'1431774127','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'162','title'=>'Соотношение мочевины и креатинина***  ','lablist'=>'1432016975','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'163','title'=>'Мочевая кислота  ','lablist'=>'1341400751','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'164','title'=>'Глюкоза  ','lablist'=>'1430395814','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'165','title'=>'Гликозилированный гемоглобин HUMAN','lablist'=>'1341384743','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'166','title'=>'Общий белок  ','lablist'=>'1341400005','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'167','title'=>'Альбумин  ','lablist'=>'1341400192','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'168','title'=>'Аммоний  ','lablist'=>'1431775302','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'169','title'=>'Лактат(LAC)  ','lablist'=>'1431775487','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'170','title'=>'Литий  ','lablist'=>'1431775603','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'171','title'=>'Белок в суточной моче  ','lablist'=>'1430634261','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'172','title'=>'Глюкоза натощак  ','lablist'=>'1341403719','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'173','title'=>'Глюкоза через 1 час после нагрузки  ','lablist'=>'1341403768','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'174','title'=>'Глюкоза через 2 часа после нагрузки  ','lablist'=>'1341403815','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'175','title'=>'(Диастаза)  ','lablist'=>'1341402874','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'176','title'=>'Тимоловая проба','lablist'=>'1341401185','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'177','title'=>'Липаза  ','lablist'=>'1341403261','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'178','title'=>'ГГТ  ','lablist'=>'1341403017','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'179','title'=>'Щелочная фосфатаза  ','lablist'=>'1341403349','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'180','title'=>'ЛДГ  ','lablist'=>'1341402914','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'181','title'=>'Холинэстераза  ','lablist'=>'1341402967','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'182','title'=>'Ферритин  ','lablist'=>'1341402784','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'183','title'=>'Витамин В 12  ','lablist'=>'1431932368','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'184','title'=>'Фолиевая кислота  ','lablist'=>'1431932418','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'185','title'=>'Железо HUMAN','lablist'=>'1341402760','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'186','title'=>'Общая Желез Способность HUMAN','lablist'=>'1341402839','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'187','title'=>'Кальций общий  ','lablist'=>'1341402584','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'188','title'=>'Фосфор  ','lablist'=>'1341402608','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'189','title'=>'Железо HUMAN','lablist'=>'1341402504','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'190','title'=>'Магний  ','lablist'=>'1341402629','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'191','title'=>'Калий  ','lablist'=>'1341402520','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'192','title'=>'Натрий  ','lablist'=>'1341402543','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'193','title'=>'Хлор  ','lablist'=>'1341402559','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'194','title'=>'Холестерол общий  ','lablist'=>'1341402013','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'195','title'=>'Триглицериды  ','lablist'=>'1341402124','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'196','title'=>'Холестерол-ЛПВП  ','lablist'=>'1341402054','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'197','title'=>'Холестерол-ЛПНП  ','lablist'=>'1341402085','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'198','title'=>'Холестерол- ЛПОНП  ','lablist'=>'1351065366','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'199','title'=>'Индекс атерогенности  ','lablist'=>'1352264258','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'200','title'=>'Ревматоидный фактор CYPESS DIAGNOSTICS','lablist'=>'1341401614','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'201','title'=>'С-реактивный белок CYPRESS DIAGNOSTICS','lablist'=>'1341401934','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'202','title'=>'Антистрептолизин-О CYPRESS DIAGNOSTICS','lablist'=>'1341401981','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'203','title'=>'Глюкоза натощак ГЛИКЕМИЧЕСКИЙ  ','lablist'=>'1431927046','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'204','title'=>'Глюкоза через 1 час после приема пищи  ','lablist'=>'1431927109','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'205','title'=>'Глюкоза через 2 час после приема пищи  ','lablist'=>'1431927149','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'206','title'=>'Морфин HUMAN','lablist'=>'1431927380','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'207','title'=>'Марихуана HUMAN','lablist'=>'1431927412','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'208','title'=>'Глюкоза  ','lablist'=>'1431776548','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'209','title'=>'Моча Мочевина  ','lablist'=>'1431776572','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'210','title'=>'Моча Креатинин  ','lablist'=>'1431776600','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'211','title'=>'Моча Мочевая кислота  ','lablist'=>'1431776632','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'212','title'=>'Мочи Белок мочи  ','lablist'=>'1431776678','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'213','title'=>'Мочи Амилаза  ','lablist'=>'1431776521','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'214','title'=>'Мочи Калий+  ','lablist'=>'1431776763','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'215','title'=>'Мочи Натрий+  ','lablist'=>'1431776788','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'216','title'=>'Мочи Фосфор  ','lablist'=>'1431776821','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'217','title'=>'Мочи Магний  ','lablist'=>'1431776841','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'218','title'=>'Мочи Ca(калций)  ','lablist'=>'1431776729','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'219','title'=>'С-пептид','lablist'=>'1432557422','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'220','title'=>'Инсулин ACCUBIND','lablist'=>'1341386903','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'221','title'=>'Инсулин DRG','lablist'=>'1341386903','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'222','title'=>'Исследование на ВИЧ-инфекцию','lablist'=>'1341483944','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'223','title'=>'Осмолярность мочи  ','lablist'=>'1433241558','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'224','title'=>'Cytomegalovirus IgG','lablist'=>'1433316509','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'225','title'=>'Albumin/globulin Ratio','lablist'=>'1433487231','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'226','title'=>'Ratio alb/glob','lablist'=>'1433487231','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'227','title'=>'АЛТ HUMAN','lablist'=>'1341400352','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'228','title'=>'Эстрадиол','lablist'=>'1341386033','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'229','title'=>'Testo Hema','lablist'=>'1341386648','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'230','title'=>'Cortizol Vitros','lablist'=>'1341385867','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'231','title'=>'Prog Vitros','lablist'=>'1341385885','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'232','title'=>'Тесто Vitros','lablist'=>'1341386648','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'233','title'=>'E2 Vitros','lablist'=>'1341386033','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'234','title'=>'  ne nujniy','lablist'=>'1341386298','goods_category'=>'1507177890','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'235','title'=>'IgE Hema','lablist'=>'1341388803','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'236','title'=>'ASSAY Pro','lablist'=>'1435806078','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'237','title'=>'Церулоплазмин','lablist'=>'1435806078','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'238','title'=>'асат','lablist'=>'1341481521','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'239','title'=>'Бак.исслед. выдел.1точ.(Vagina)','lablist'=>'1435926233','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'240','title'=>'афс IgG','lablist'=>'1435849004','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'241','title'=>'FSH -  ','lablist'=>'1341385990','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'242','title'=>'LCA Index','lablist'=>'1436847829','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'243','title'=>'Vitros','lablist'=>'1341387817','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'244','title'=>'Свободный эстриол Хема','lablist'=>'1431931145','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'245','title'=>'Кортизол в моче','lablist'=>'1438775004','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'246','title'=>'ВПЧ комплекс','lablist'=>'1431943504','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'247','title'=>'Вирус папиломы','lablist'=>'1431943399','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'248','title'=>'Вирус папиломы (HPV6/11)','lablist'=>'1431943441','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'249','title'=>'Бак.исслед. крови на стерильность','lablist'=>'1341487014','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'250','title'=>'Токсоплазма','lablist'=>'1439371280','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'251','title'=>'Гепатит ','lablist'=>'1431942423','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'252','title'=>'Гепатит ','lablist'=>'1431942451','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'253','title'=>'Гепатит ','lablist'=>'1431942489','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'254','title'=>'Гепатит ','lablist'=>'1431942514','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'255','title'=>'Вирус простого герпеса тип 1,2 кровь','lablist'=>'1439371456','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'256','title'=>'Цитомегаловирус Кровь','lablist'=>'1439371398','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'257','title'=>'Эпштейн-Барр вирус','lablist'=>'1439371543','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'258','title'=>'RW ИФА','lablist'=>'1341483794','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'259','title'=>'ЛДГ (Sypress)','lablist'=>'1341402914','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'260','title'=>'Na Sypress','lablist'=>'1341402543','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'261','title'=>'Na Sypress','lablist'=>'1341402543','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'262','title'=>'К Sypress','lablist'=>'1341402520','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'263','title'=>'Mg Sypress','lablist'=>'1341402629','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'264','title'=>'CK Sypress','lablist'=>'1341400474','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'265','title'=>'Хлор Sypress','lablist'=>'1341402559','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'266','title'=>'Щелочная фосфатаза Sypress','lablist'=>'1341403349','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'267','title'=>'ГГТ Sypress','lablist'=>'1341403017','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'268','title'=>'Амилаза Sypress','lablist'=>'1341402874','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'269','title'=>'Мочевая кислота Sypress','lablist'=>'1341400751','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'270','title'=>'Кальций общий Sypress','lablist'=>'1341402584','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'271','title'=>'FT 4 Hema','lablist'=>'1341386525','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'272','title'=>'Пролактин 2','lablist'=>'1341385903','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'273','title'=>'ОАМ','lablist'=>'1341481711','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'274','title'=>'пр','lablist'=>'1415776343','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'275','title'=>'нар.','lablist'=>'1438428890','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'276','title'=>'зим.','lablist'=>'1341481782','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'277','title'=>'неч','lablist'=>'1341481758','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'278','title'=>'нечип.','lablist'=>'1431929377','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'279','title'=>'3ех','lablist'=>'1355546853','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'280','title'=>'пигм.','lablist'=>'1341481826','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'281','title'=>'сп','lablist'=>'1341478089','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'282','title'=>'сек.','lablist'=>'1341478139','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'283','title'=>'ур.','lablist'=>'1431928531','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'284','title'=>'коль.','lablist'=>'1431928458','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'285','title'=>'цитог.','lablist'=>'1341477605','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'286','title'=>'шув.','lablist'=>'1341481027','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'287','title'=>'Вектор-Бест','lablist'=>'1448006726','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'288','title'=>'Sypress','lablist'=>'1431776521','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'289','title'=>'Амилаза HUMAN','lablist'=>'1341402874','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'290','title'=>'HUMAN','lablist'=>'1431776521','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'291','title'=>'гельминты','lablist'=>'1450760727','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'292','title'=>'гельминты','lablist'=>'1450760773','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'293','title'=>'гельминты','lablist'=>'1450760807','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'294','title'=>'гельминты','lablist'=>'1448006529','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'295','title'=>'тест','lablist'=>'1447063333','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'296','title'=>'Вектор-Бест','lablist'=>'1341402784','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'297','title'=>'наркотест','lablist'=>'1438428890','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'298','title'=>'наркотест','lablist'=>'1455697837','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'299','title'=>'Гепатит D количественный[Гепатит D ]','lablist'=>'1456905719','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'300','title'=>'бак пос сок прост','lablist'=>'1341487262','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'301','title'=>'грибок из ногтей','lablist'=>'1391156279','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'302','title'=>'ПСФИР-1','lablist'=>'1462250475','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'303','title'=>'Белок-1 связывающий ИФР','lablist'=>'1462253189','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'304','title'=>'Трипсиноген-2','lablist'=>'1462256454','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'305','title'=>'СОЭ','lablist'=>'1432017801','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'306','title'=>'Sex hormone (DBC)','lablist'=>'1404551817','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'307','title'=>'Blood group','lablist'=>'1341385065','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'308','title'=>'ГГТ HUMAN','lablist'=>'1341403017','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'309','title'=>'гонорея','lablist'=>'1431943243','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'310','title'=>'АТТГ-Алкор-био','lablist'=>'1372917846','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'311','title'=>'ХГЧ ','lablist'=>'1431931220','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'312','title'=>'ХГЧ - Алкор','lablist'=>'1431931220','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'313','title'=>'Пролактин - Алкор','lablist'=>'1341385903','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'314','title'=>'DHEAS ALKOR','lablist'=>'1341386885','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'315','title'=>'17 Alkor','lablist'=>'1341387459','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'316','title'=>'ВПГ авидность Вектор-Бест','lablist'=>'1478695699','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'317','title'=>'ЦМВ авидность Вектор-Бест','lablist'=>'1478695534','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'318','title'=>'HBs Ag по оптической плотности','lablist'=>'1341388948','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'319','title'=>'Аnti - НCV по оптической плотности','lablist'=>'1341389226','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'320','title'=>'АТТПО-алкор','lablist'=>'1431762322','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'321','title'=>'АМА-М2','lablist'=>'1478349723','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'322','title'=>'CA 72-4','lablist'=>'1490945584','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'323','title'=>'NSE','lablist'=>'1490945926','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'324','title'=>'HE4','lablist'=>'1490857528','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'325','title'=>'Креа','lablist'=>'1490856522','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'326','title'=>'RBC','lablist'=>'1341384572','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'327','title'=>'HGB','lablist'=>'1490950416','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'328','title'=>'WBC','lablist'=>'1490950468','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'329','title'=>'Нейтрофилы','lablist'=>'1490951125','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'330','title'=>'НейтрПал','lablist'=>'1490951190','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'331','title'=>'Моноцит','lablist'=>'1490951299','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'332','title'=>'Лимфоцит','lablist'=>'1490951283','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'333','title'=>'Базофи','lablist'=>'1490951271','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'334','title'=>'Эозиноф','lablist'=>'1490951253','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'335','title'=>'ESR','lablist'=>'1490951618','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'336','title'=>'RDW-SD','lablist'=>'1490951604','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'337','title'=>'RDW-CV','lablist'=>'1490951590','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'338','title'=>'MCHC','lablist'=>'1490951576','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'339','title'=>'MCH','lablist'=>'1490951564','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'340','title'=>'MCV','lablist'=>'1490951553','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'341','title'=>'HCT','lablist'=>'1490951543','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'342','title'=>'LCR','lablist'=>'1490951533','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'343','title'=>'LCC','lablist'=>'1490951522','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'344','title'=>'1.08-2.82','lablist'=>'1490951510','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'1']);
        $this->insert('{{%tb_methods}}',['id'=>'345','title'=>'PDW','lablist'=>'1490951497','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'346','title'=>'MPV','lablist'=>'1490951487','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'347','title'=>'PLT','lablist'=>'1490951474','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'348','title'=>'HGB','lablist'=>'1490780406','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'349','title'=>'RF','lablist'=>'1490789151','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'350','title'=>'ASLO','lablist'=>'1490953670','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'351','title'=>'CRP','lablist'=>'1490953657','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'352','title'=>'Her I LgG','lablist'=>'1490782811','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'353','title'=>'HSV II IgM','lablist'=>'1490783050','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'354','title'=>'HSV-1 IgM','lablist'=>'1490783036','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'355','title'=>'Микроальбумин','lablist'=>'1341481916','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'356','title'=>'АДФ','lablist'=>'1490780985','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'357','title'=>'АДФ 1','lablist'=>'1491979118','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'358','title'=>'Глюкоза','lablist'=>'1490853358','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'359','title'=>'Глюкоза2 час','lablist'=>'1490853372','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'360','title'=>'Herpes 1/2 IgA','lablist'=>'1490783176','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'361','title'=>'Chl IgA','lablist'=>'1490783215','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'362','title'=>'Myc IgA','lablist'=>'1491980513','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'363','title'=>'Chl IgM','lablist'=>'1490783850','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'364','title'=>'MycIgM','lablist'=>'1490783912','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'365','title'=>'MycIg А','lablist'=>'1490783889','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'366','title'=>'MycIgG','lablist'=>'1490783900','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'367','title'=>'HelIgM','lablist'=>'1490784001','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'368','title'=>'HelIgG','lablist'=>'1490783993','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'369','title'=>'GarIgG','lablist'=>'1490784034','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'370','title'=>'GarIgM','lablist'=>'1490784048','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'371','title'=>'TriIgM','lablist'=>'1490784103','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'372','title'=>'ЛяlgG','lablist'=>'1490785447','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'373','title'=>'ЛяlgA','lablist'=>'1490785441','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'374','title'=>'ЛяlgM','lablist'=>'1490785455','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'375','title'=>'Кортизол в слюне','lablist'=>'1490855557','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'376','title'=>'Candida (Мазок)','lablist'=>'1490788438','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'377','title'=>'Chlamydia trachomatis (Мазок)','lablist'=>'1490788403','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'378','title'=>'Cytomegalovirus (Мазок)','lablist'=>'1490788368','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'379','title'=>'Herpis Simplex 1 (Мазок)','lablist'=>'1490788386','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'380','title'=>'Herpis Simplex 2 (Мазок)','lablist'=>'1490788395','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'381','title'=>'Mycoplasma homins (Мазок)','lablist'=>'1490788413','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'382','title'=>'Rubella','lablist'=>'1490788377','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'383','title'=>'Toxoplasma (Мазок)','lablist'=>'1490788360','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'384','title'=>'Ureaplasma urealyticum','lablist'=>'1490788421','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'385','title'=>'HPV','lablist'=>'1490788461','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'386','title'=>'1618','lablist'=>'1490788471','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'387','title'=>'3133','lablist'=>'1490788479','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'388','title'=>'B12','lablist'=>'1493269447','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'389','title'=>'Глюкоза','lablist'=>'1490788627','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'390','title'=>'SCC','lablist'=>'1493351548','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'391','title'=>'HAV IgG','lablist'=>'1490857804','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'392','title'=>'ВПЧ 3133','lablist'=>'1490788151','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'393','title'=>'ВПЧ 1618','lablist'=>'1490788138','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'394','title'=>'HPV','lablist'=>'1490788128','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'395','title'=>'Ureaplasma urealyticum','lablist'=>'1490788118','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'396','title'=>'Rubella','lablist'=>'1490788055','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'397','title'=>'Mycoplasma ','lablist'=>'1490788108','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'398','title'=>'Herpis Simplex 1','lablist'=>'1490788075','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'399','title'=>'Herpis Simplex 1','lablist'=>'1490788066','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'400','title'=>'HCV','lablist'=>'1490788175','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'401','title'=>'HBV','lablist'=>'1490788165','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'402','title'=>'Cytomegalovirus','lablist'=>'1490788045','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'403','title'=>'Chlamydia ','lablist'=>'1490788096','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'404','title'=>'Candida','lablist'=>'1490788190','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'405','title'=>'HelicoPyl','lablist'=>'1490789233','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'406','title'=>'Toxoplasma (Кровь)','lablist'=>'1490788038','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'407','title'=>'Тироксинсвязывающая способность сыворотки (Т3 Uptake)','lablist'=>'1490855478','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'408','title'=>'Лямблии в кале','lablist'=>'1492241645','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'409','title'=>'СКМВ','lablist'=>'1490856539','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'410','title'=>'Ацетон','lablist'=>'1490854755','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'411','title'=>'Хлор[Cl] в суточной моче','lablist'=>'1490854682','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'412','title'=>'ХГЧМ','lablist'=>'1490854109','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'413','title'=>'HBe-Ab','lablist'=>'1497529709','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'414','title'=>'Дюке','lablist'=>'1497516137','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'415','title'=>'LE','lablist'=>'1497515929','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'416','title'=>'Тропонин I','lablist'=>'1497511358','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'417','title'=>'2 Риагент','lablist'=>'1341388529','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'418','title'=>'Кортизол 2','lablist'=>'1341385867','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'419','title'=>'Свободный тестостерон HEMA','lablist'=>'1341386706','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'420','title'=>'АЦЦП','lablist'=>'1498041744','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'421','title'=>'Ure IgA','lablist'=>'1498042255','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'422','title'=>'HEV','lablist'=>'1498042580','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'423','title'=>'HBsAg','lablist'=>'1498042761','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'424','title'=>'Просфос','lablist'=>'1490856918','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'425','title'=>'Миелоциты %','lablist'=>'1498050992','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'426','title'=>'Метамиелоциты','lablist'=>'1498051045','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'427','title'=>'Плазмоклетки','lablist'=>'1498051311','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'428','title'=>'Абсколэоз','lablist'=>'1498051378','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'429','title'=>'RBC','lablist'=>'1498102481','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'430','title'=>'HGB','lablist'=>'1498102494','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'431','title'=>'WBC','lablist'=>'1498102505','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'432','title'=>'Миелоциты ','lablist'=>'1498102524','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'433','title'=>'Метамиелоциты','lablist'=>'1498102539','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'434','title'=>'Палочкоядерные нейтрофилы','lablist'=>'1498102555','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'435','title'=>'Сегментоядерные нейтрофилы','lablist'=>'1498102571','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'436','title'=>'Эозинофилы','lablist'=>'1498102581','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'437','title'=>'Базофилы ','lablist'=>'1498102597','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'438','title'=>'Лимфоциты ','lablist'=>'1498102607','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'439','title'=>'Моноциты ','lablist'=>'1498102617','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'440','title'=>'Моноциты ','lablist'=>'1498102617','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'441','title'=>'Плазмотические клетки','lablist'=>'1498102628','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'442','title'=>'Абсолютное количество эозинофилов','lablist'=>'1498102648','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'443','title'=>'Тромбоциты ','lablist'=>'1498102657','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'444','title'=>'Средний объем тромбоцитов ','lablist'=>'1498102668','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'445','title'=>'Ширина распределения тромбоцитов','lablist'=>'1498102677','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'446','title'=>'PCT','lablist'=>'1498102687','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'447','title'=>'Гемотокрит','lablist'=>'1498102698','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'448','title'=>'Средний объем эритроцита','lablist'=>'1498102710','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'449','title'=>'Среднее содержание гемоглобина в эритроците','lablist'=>'1498102721','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'450','title'=>'Средняя когцентрация гемоглобина в эритроците','lablist'=>'1498102733','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'451','title'=>'RDW-CV','lablist'=>'1498102744','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'452','title'=>'RDW-SD','lablist'=>'1498102757','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'453','title'=>'ESR','lablist'=>'1498102768','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'454','title'=>'HIV','lablist'=>'1499087249','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'455','title'=>'Хема','lablist'=>'1341385990','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'456','title'=>'Хема','lablist'=>'1430206456','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'457','title'=>'Хема','lablist'=>'1341387459','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'458','title'=>'хема','lablist'=>'1341386525','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'459','title'=>'Хема','lablist'=>'1341386453','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'460','title'=>'Им-Ди','lablist'=>'1490785447','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'461','title'=>'Им-Ди','lablist'=>'1341388529','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'462','title'=>'Хема','lablist'=>'1433316509','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'463','title'=>'Дс Ифа','lablist'=>'1341386648','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'464','title'=>'Хема','lablist'=>'1341385903','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'465','title'=>'HSV G Xema','lablist'=>'1341395856','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'466','title'=>'HSV S XEMA','lablist'=>'1490782811','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'467','title'=>'HSV G Xema','lablist'=>'1341395420','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'468','title'=>'Rubella Ig G DC','lablist'=>'1341391434','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'469','title'=>'Gardntr V. Ig G','lablist'=>'1490784034','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'470','title'=>'HAV IgG','lablist'=>'1490857804','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'471','title'=>'HSV IgM Хема','lablist'=>'1490783036','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'472','title'=>'HSV IgM Хема','lablist'=>'1490783050','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);
        $this->insert('{{%tb_methods}}',['id'=>'473','title'=>'Копрология','lablist'=>'1341486109','goods_category'=>'0','prime_price'=>'0','price'=>'0','active'=>'0','status'=>'0']);

        $this->createIndex('idx_lablist_9322_12','tb_methods','lablist',0);
        $this->createIndex('idx_title_9322_13','tb_methods','title',0);
    }

    public function safeDown()
    {
        $this->dropTable('{{%tb_methods}}');
    }
}
